version: '3.6'
services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: ${DB_CONTAINER_IMAGE}
    command: --max_allowed_packet=${DB_MAX_PACKET} --slave_max_allowed_packet=${DB_MAX_PACKET} --innodb_buffer_pool_size=${DB_BUFFER_MEMORY} --innodb_log_file_size=${DB_LOG_SIZE} --innodb_log_buffer_size=${DB_LOG_BUFFER_SIZE} --key_buffer_size=${DB_KEY_BUFFER} --myisam_sort_buffer_size=${DB_SORT_BUFFER} --read_buffer_size=${DB_READ_BUFFER} --read_rnd_buffer_size=${DB_READ_RND_BUFFER} --thread_stack=${DB_THREAD_STACK} --thread_cache_size=8 --query_cache_limit=${DB_QUERY_CACHE_LIMIT} --query_cache_size=${DB_QUERY_CACHE_SIZE} --innodb_buffer_pool_instances=${DB_BUFFER_POOLS} --max_heap_table_size=134217728 --tmp_table_size=134217728 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    build:
      context: ./.docker/db
      dockerfile: Dockerfile
    networks:
      - network
    logging:
      driver: none
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
  host:
    container_name: ${HOST_CONTAINER_NAME}
    hostname: ${HOST_NAME}
    image: ${HOST_CONTAINER_IMAGE}
    build:
      context: ./.docker/host
      dockerfile: Dockerfile
    networks:
      - network
    logging:
      driver: none
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - MYSQL_HOST=${DB_CONTAINER_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} 
    volumes:
      - ./${DOCUMENT_ROOT}:/var/www/html/
      - ./${PHP_INI}:/usr/local/etc/php/php.ini
      - ./${APACHE_PREFORK}:/etc/apache2/mods-available/mpm_prefork.conf
      - tempdata:/var/www/html/${TEMP_DIR}
      - tempdata2:/var/www/html/${TEMP_DIR2}
      - storagedata:/var/www/html/${UPLOADS_DIR}
      - avatars:/var/www/html/${AVATARS_DIR}
    ports:
      - ${HOST_PORT}:80
  phpmyadmin:
    container_name: ${DBADMIN_CONTAINER_NAME}
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    volumes:
      - ./.docker/dbadmin/mpm_prefork.conf:/etc/apache2/mods-available/mpm_prefork.conf
    ports:
      - ${DBDBADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_CONTAINER_NAME}
      - UPLOAD_LIMIT=2048000k
    networks:
      - network
    depends_on:
      - db 
volumes:
  dbdata:
    name: ${HOST_CONTAINER_NAME}-dbdata
    driver: local  
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/VOLUMES/wallpapercropper-v2-web/dbdata'
  storagedata:
    name: ${HOST_CONTAINER_NAME}-storagedata
    driver: local  
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/VOLUMES/wallpapercropper-v2-web/storagedata'
  avatars:
    name: ${HOST_CONTAINER_NAME}-avatars
    driver: local  
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/VOLUMES/wallpapercropper-v2-web/avatars'
  tempdata:
    name: ${HOST_CONTAINER_NAME}-tempdata
  tempdata2:
    name: ${HOST_CONTAINER_NAME}-tempdata2
networks:
  network:
    driver: bridge